# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'GenericProjectForSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GenericProjectForSwift

  pod 'SnapKit'
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'SwiftyJSON'
  pod 'IQKeyboardManagerSwift'
  pod 'ReachabilitySwift'
  pod 'EmptyDataSet-Swift'
  pod 'YYKit'
  pod 'MJRefresh'
  pod 'SVProgressHUD'
  pod 'IDealist'
end
